import { Geist, Geist_Mono } from "next/font/google";
import "./../../globals.css";
import Header from "@/Components/Common/Header";
import Footer from "@/Components/Common/Footer";
import ContractorHeader from "@/Components/Contractor/ContractorHeader";

const geistSans = Geist({
    variable: "--font-geist-sans", 
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Contractor Dashboard",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {

    return (
        <div className="container">
            <ContractorHeader />
            <hr className="border border-[#ececec] my-5 " />
            <div className="z-[9] relative">
                {children}
            </div>
        </div>
    );
}
