
import "./../../globals.css";


export const metadata = {
    title: "Custom Website",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {

    return (
        <div className="container">
            {children}
        </div>
    );
}
