import SubContractorHeader from "@/Components/SubContractor/SubContractorHeader";
import "./../../globals.css";

export const metadata = {
    title: "Contractor Dashboard",
    description: "Generated by create next app",
};

// not root layout this is main layout

export default function Layout({ children }) {

    return (
        <div className="container">
            <SubContractorHeader />
            <hr className="border border-[#ececec] my-5 " />
            <div className="z-[9] relative">
                {children}
            </div>
        </div>
    );
}